name: my_tree_links
description: "My tree link chrome extension"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  change_case: ^1.1.0
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  font_awesome_flutter: ^10.6.0
  form_builder_validators: ^9.1.0
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/png/
